// <auto-generated />
using FavoriteFilmsMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FavoriteFilmsMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260826122707_CleanInitial")]
    partial class CleanInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FavoriteFilmsMVC.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Наше время на Земле подошло к концу, команда исследователей берется за самую важную миссию в истории человечества.",
                            Director = "Кристофер Нолан",
                            Genre = "Фантастика",
                            PosterUrl = "https://upload.wikimedia.org/wikipedia/ru/c/c3/Interstellar_film_poster.jpg",
                            ReleaseYear = 2014,
                            Title = "Интерстеллар"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Бэтмен поднимает ставки в войне с криминалом с помощью лейтенанта Джима Гордона и прокурора Харви Дента.",
                            Director = "Кристофер Нолан",
                            Genre = "Боевик",
                            PosterUrl = "https://upload.wikimedia.org/wikipedia/ru/1/15/Dark_knight_poster.jpg",
                            ReleaseYear = 2008,
                            Title = "Темный рыцарь"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Вор, крадущий корпоративные секреты через использование технологии обмена снами.",
                            Director = "Кристофер Нолан",
                            Genre = "Фантастика",
                            PosterUrl = "https://upload.wikimedia.org/wikipedia/ru/c/bc/Inception_poster.jpg",
                            ReleaseYear = 2010,
                            Title = "Начало"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Компьютерный хакер узнает от таинственных повстанцев об истинной природе его реальности.",
                            Director = "Лана и Лилли Вачовски",
                            Genre = "Фантастика",
                            PosterUrl = "https://upload.wikimedia.org/wikipedia/ru/9/9d/Matrix-dvd.jpg",
                            ReleaseYear = 1999,
                            Title = "Матрица"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Офисный работник, страдающий бессонницей, и харизматичный мыловар создают подпольный бойцовский клуб.",
                            Director = "Дэвид Финчер",
                            Genre = "Драма",
                            PosterUrl = "https://upload.wikimedia.org/wikipedia/ru/8/8b/Fight_Club_poster.jpg",
                            ReleaseYear = 1999,
                            Title = "Бойцовский клуб"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Истории двух бандитов, жены их босса и боксера переплетаются в серии философских и комичных событий.",
                            Director = "Квентин Тарантино",
                            Genre = "Криминал",
                            PosterUrl = "https://upload.wikimedia.org/wikipedia/ru/9/93/Pulp_Fiction_cover.jpg",
                            ReleaseYear = 1994,
                            Title = "Криминальное чтиво"
                        },
                        new
                        {
                            Id = 7,
                            Description = "История надзирателей в блоке смертников, один из которых обладает чудесным даром исцеления.",
                            Director = "Фрэнк Дарабонт",
                            Genre = "Драма",
                            PosterUrl = "https://upload.wikimedia.org/wikipedia/ru/c/c5/Green_mile_poster.jpg",
                            ReleaseYear = 1999,
                            Title = "Зеленая миля"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Успешный банкир осужден за убийство и отправлен в тюрьму Шоушенк.",
                            Director = "Фрэнк Дарабонт",
                            Genre = "Драма",
                            PosterUrl = "https://upload.wikimedia.org/wikipedia/ru/d/de/ShawshankRedemptionMoviePoster.jpg",
                            ReleaseYear = 1994,
                            Title = "Побег из Шоушенка"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Два судебных пристава отправляются на остров в психиатрическую больницу для расследования исчезновения пациентки.",
                            Director = "Мартин Скорсезе",
                            Genre = "Детектив",
                            PosterUrl = "https://upload.wikimedia.org/wikipedia/ru/a/a2/Shutter-island-poster.jpg",
                            ReleaseYear = 2010,
                            Title = "Остров проклятых"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Наследник знаменитого дома Атрейдесов отправляется на самую опасную планету во Вселенной — Арракис.",
                            Director = "Дени Вильнёв",
                            Genre = "Фантастика",
                            PosterUrl = "https://upload.wikimedia.org/wikipedia/ru/d/d5/Dune_2021_poster.jpg",
                            ReleaseYear = 2021,
                            Title = "Дюна"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
